### ISSUE TITLE
Advanced workshops

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#139]
## Description

The idea is simple: we need more advanced workshops as part of SciProg to complement the introductory ones we've been hosting. It has come up previously (see #89), but nothing came out of it. The recent success of the [two-day workshops](http://www.lib.sfu.ca/about/branches-depts/rc/research/software/31556) on advanced modelling in R highlight the need for more advanced workshops. This issue will track SciProg's progress to make it happen. 
## Tasks
- [ ] Clarify funding with Nicole / @brunogrande
- [ ] Ask Marinde Out for pointers from organizing the advanced modelling R workshop
- [ ] Get list of speakers who will be already on-site / @vguerracanedo 
- [ ] Get list of possible topics / @sciprog-sfu/organizers 
- [ ] Email faculty/post-docs for existing lessons 
## Tips
- Establish pre-requirements for the workshop
- Focus on methods (_e.g._ generalized linear mixed-effects modelling) for it to be broadly relevant

**Comment by vguerracanedo** [comment]
Here are a few speakers coming to the area
- Biology seminar SFU: http://advance.science.sfu.ca/events/recordlist.php?-skip=0&-sortfieldone=Date&-max=50&-sortorderone=ascend
- MBB seminar SFU calendar: https://events.sfu.ca/View.html?calendar_id=11
- Biodiversity Research Seminar UBC: http://www.zoology.ubc.ca/brs/

**Comment by BrunoGrandePhD** [comment]
## Possible topics
- Machine learning (_e.g._ random forest, SVM)
- RNA-seq gene expression analysis (_e.g._ differential expression)
- NGS data analysis (_e.g._ variant calling, assembly)
- Visualization, _e.g._ by Martin K

## Similar Workshops
- [UC Davis Bioinformatics Core Training Events](http://bioinformatics.ucdavis.edu/training/events/)
- [Joint Genome Institute Workshops](http://jgi.doe.gov/events/)
- [Friday Harbor Workshops](http://depts.washington.edu/fhl/studentSummer2015.html)
- [Bioinformatics.ca Workshops](https://bioinformatics.ca/workshops/2016)

**N.B.** Many of the items listed above were copied from @vguerracanedo's email.

**Comment by vguerracanedo** [comment]
Would bioinformatic software such as samtools, bowtie, tophat, cufflinks, IGV, RAxML, etc be too specific for possible topics? We could explore subjects such as haplotype phasing and/or building trees with big data sets. 
V

**Comment by BrunoGrandePhD** [comment]
@vguerracanedo: I think it would be best to structure the workshops around applications of those tools. For instance, a workshop on phylogenetic analysis or RNA-seq analysis could use the tools you mentioned and remain broadly relevant. People would know whether they need to learn how to perform RNA-seq analyses, while they might not know that they need to learn how to use samtools. In other words, the tools would be covered, but that wouldn't be the way we would pitch the workshop.

**Comment by BrunoGrandePhD** [comment]
We should put together a reasonable list of topics and send it out to SciProg to gauge interest. We can use this information to inform our decision for which workshop to organize first.

**Comment by BrunoGrandePhD** [comment]
@vguerracanedo: Do you want to meet with Marinde to get an idea of what needs to be done to pull off something like this? I can take care of talking with Nicole to clarify funding.

**Comment by vguerracanedo** [comment]
Great! And yes, I can follow up with the "Student Organizing Committee for Advanced Statistical Workshops in R".

V

**Comment by SimonGoring** [comment]
Hi all, here's the list of speakers/sessions that we're looking at for the UBC Group:

https://github.com/minisciencegirl/studyGroup/issues/134

I think many speakers might be willing to to run their session at SFU as well.

**Comment by BrunoGrandePhD** [comment]
Thanks, @SimonGoring!

**Comment by vguerracanedo** [comment]
I can teach a workshop on any of the subjects related to bioinformatics noted below next semester (Spring 2017). This workshops could be given a session before the advance workshops on related subjects. 

Basic
- How RNA-seq or ddRAD-seq libraries are put together
- Introduction to RNA sequencing data (FASTA, FASTQ, Base Quality, Nucleotide Codes) 

Medium level
- High through put data quality check and data clean up
- De novo assemblies of RNA-seq libraries (approaches based on data type, figuring out the computation resources needed, etc). Assembly Quality Assessments 
- RNA-seq transcript quantification, biological replications and differential expression (with and without biological replications)
- Functional annotation 
  Note: I work with perl and bash (occasionally with R). 

I can also lead workshops in common population genetics programs/approaches (sequences trimming with chromatograms, alignments, Arlequin, Dnasp, Mega, Mr Bayes, etc). 

Here are some additional suggestions for possible advanced workshops
- Building phylogenetic trees of multiple genes
- Isolation with migration models
- Phasing genes of non-model organisms (no genomes)

**Comment by BrunoGrandePhD** [comment]
There is a group of students in biology/E2O at SFU who are organizing an advanced R workshop on modelling. We asked them for feedback on the process of putting together such a workshop. I'm consolidating their responses below for reference. 

> - identify a need for a workshop. we sent out a survey to stats beerz to see which stats models they wanted to learn about. GLMMs had the biggest interest.
> - get together a committee - so you don't have to do it all on your own
> - write a proposal for funding - we applied to SPICES, but it got rejected - then asked Research COmmons  - Nicole White. they were happy to help organise and put on the workshop and pay for the teacher. it required a bit of negotiation depending on if the teacher was internal or external. The Reseach Commons require that the workshop is open to all SFU students. Also they don't like you calling it a 'course' - it has to be a workshop, to avoid confusion with actual classes.
> - find the teacher and get them to develop the content
> - we started applying for this in March or so - its taken a while to get it running because we initially didn't get funding.
> - research commons did all the advertising.
> - we were also talking to the BICS and REM heads to get funding through the deptartments. that was of varied success. There was also options through the Grad funding ... not sure of details - the others know more about them.
> - we tossed up between 2 full day workshops or a more shorter days over a few weeks - this model seems easiest to organise.
> - we asked around for helpers for the day - volunteers.
> - Research commons said that attendence is higher if you make them pay for the course - ours was $21 for the two days including lunch.
> - we will try to get another one running next year as many people missed out on getting a spot. But not sure the source of funding.
>   is hard to have a workshop that would be good for everyone. And it takes a lot of effort to communicate this to the funding sources. 
> - There is a disconnect between what is being taught at SFU (and other universities), and what it is required for publishing. 
> - We have professors on site that could teach the advanced subjects of interest, but these professors are not available to teach the courses for a variety of reasons.
> - The demand of subjects for potential workshops was established through meetings with a variety of groups (stats groups, bio caucus, ocean group, etc) 
> - A lot of graduate students in the science departments already have (at least) basic training in R and other programming languages. And there is an assumption that basic training in a programming language is enough to figure out the methods needed for their specific research within unrealistic times. 
> - The Bio department was willing to fund the workshop tuition of their students, and this may be the case for other departments too. 
> - A lot of people that wanted to be in the advanced stats workshop in R were not able to get in.

**Comment by BrunoGrandePhD** [comment]
@vguerracanedo reported a funding opportunity that looks promising!

> I just had an informal talk with an IRMACS rep about the potential of getting funding for bioinformatic workshops, and they told me that there may be some funding for that!!!! Woot woot! 
> 
> We would need to 1) define subjects of interest, 2) meet with them, 3) write a proposal (it sounds like it would be a short proposal - they understand the importance of bioinformatics). 
> 
> IRMACS is a center for multidisciplinary studies, so I this falls right on their alley.
